[project]
name = 'Tokenized-Travel-Dynamic-Pricing-Optimization'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.customer-segmentation]
path = 'contracts/customer-segmentation.clar'
clarity_version = 2
epoch = 2.5

[contracts.demand-forecasting]
path = 'contracts/demand-forecasting.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
